basePath: /api/v1
definitions:
  github_com_splekhanov_go-simple-crud_internal_model.Movie:
    properties:
      country:
        type: string
      director:
        type: string
      genre:
        type: string
      title:
        example: The Thing
        format: string
        type: string
      year:
        type: string
    type: object
  httputil.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /movies:
    post:
      consumes:
      - application/json
      description: create a new movie
      parameters:
      - description: Add movie
        in: body
        name: movie
        required: true
        schema:
          $ref: '#/definitions/github_com_splekhanov_go-simple-crud_internal_model.Movie'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_splekhanov_go-simple-crud_internal_model.Movie'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Creates a movie
      tags:
      - movies
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
