basePath: /api/v1
definitions:
  github_com_splekhanov_go-simple-crud_internal_models.Movie:
    properties:
      country:
        type: string
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      director:
        type: string
      genre:
        type: string
      id:
        type: integer
      title:
        type: string
      updatedAt:
        type: string
      year:
        type: string
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /movies:
    post:
      consumes:
      - application/json
      description: create a new movie
      parameters:
      - description: Movie ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_splekhanov_go-simple-crud_internal_models.Movie'
      summary: Creates a movie
      tags:
      - movies
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
